<?php
/**
 * MyBB 1.8 Italiano Language Pack
 * Copyright 2023 Cesarinik, All Rights Reserved
 *
 */

$l['board_settings'] = 'Impostazioni del forum';
$l['change_settings'] = 'Modifica impostazioni';
$l['change_settings_desc'] = 'In questa sezione puoi gestire varie impostazioni della tua Board. per iniziare, seleziona un gruppo di impostazioni e controlla le relative impostazioni.';
$l['add_new_setting'] = 'Aggiungi nuove impostazioni';
$l['add_new_setting_desc'] = 'In questa sezione puoi aggiungere ulteriori impostazioni alla tua board.';
$l['modify_existing_settings'] = 'Modifica impostazioni';
$l['modify_existing_settings_desc'] = 'In questa sezione puoi modificare le impostazioni presenti sulla tua board';
$l['add_new_setting_group'] = 'Aggiungi gruppo di impostazioni';
$l['add_new_setting_group_desc'] = 'In questa sezione puoi creare un gruppo per catalogare le nuove impostazioni della Board.';
$l['edit_setting_group'] = 'Modifica gruppo delle impostazioni.';
$l['edit_setting_group_desc'] = 'In questa sezione puoi modificare un gruppo di impostazioni';
$l['title'] = 'Titolo';
$l['description'] = 'Descrizione';
$l['group'] = 'Gruppo';
$l['display_order'] = 'Ordine di visualizzazione';
$l['name'] = 'Identificativo';
$l['name_desc'] = 'Questo identificativo univoco viene impostato in un array delle impostazioni per identificare le impostazioni (temi, script, plugin, traduzioni).';
$l['group_name_desc'] = 'Questo identificativo unico è usato per identificare la traduzione.';
$l['text'] = 'Testo';
$l['numeric_text'] = 'Testo numerico';
$l['textarea'] = 'Area di testo';
$l['yesno'] = 'Scelta Si/No';
$l['onoff'] = 'Scelta On/Off';
$l['select'] = 'Box di selezione';
$l['radio'] = 'Pulsanti radio';
$l['checkbox'] = 'Casella di controllo';
$l['language_selection_box'] = 'Box di selezione lingua';
$l['forum_selection_box'] = 'Box di selezione forum';
$l['forum_selection_single'] = 'Box di selezione forum singola';
$l['group_selection_box'] = 'Box di selezione gruppo';
$l['group_selection_single'] = 'Box di selezione gruppo singola';
$l['adminlanguage'] = 'Selezione lingua amministrazione';
$l['cpstyle'] = 'Stile pannello di controllo';
$l['prefix_selection_box'] = 'Selezione del prefisso';
$l['php'] = 'Valutato da PHP';
$l['type'] = 'Tipo';
$l['extra'] = 'Extra';
$l['extra_desc'] = 'Se questa impostazione selezionata è radio o casella di controllo inserisci la chiave (chiave=articolo) della lista da visualizzare. Separa le voci una per linea, se è PHP, inserisci il PHP da valutare.';
$l['value'] = 'Valore';
$l['insert_new_setting'] = 'Inserisci una nuova impostazione';
$l['edit_setting'] = 'Modifica impostazione';
$l['delete_setting'] = 'Elimina impostazione';
$l['setting_configuration'] = 'Configurazione impostazioni';
$l['update_setting'] = 'Aggiorna impostazioni';
$l['save_settings'] = 'Salva impostazioni';
$l['setting_groups'] = 'Gruppo impostazioni';
$l['bbsettings'] = 'Impostazioni';
$l['insert_new_setting_group'] = 'Inserisci un nuovo gruppo di impostazioni';
$l['setting_group_setting'] = 'Gruppo impostazioni / impostazioni';
$l['order'] = 'Ordine';
$l['delete_setting_group'] = 'Elimina gruppo impostazioni';
$l['save_display_orders'] = 'Salva ordine di visualizzazione';
$l['update_setting_group'] = 'Aggiorna gruppo impostazioni';
$l['modify_setting'] = 'Modifica impostazioni';
$l['search'] = 'Cerca';
$l['plugin_settings'] = 'Impostazioni Plugin';
$l['show_all_settings'] = 'Mostra tutte le impostazioni';
$l['settings_search'] = 'Cerca per impostazione';
$l['confirm_setting_group_deletion'] = 'Sei sicuro di voler eliminare questo gruppo di impostazioni?';
$l['confirm_setting_deletion'] = 'Sei sicuro di voler eliminare questa impostazione?';
$l['error_format_dimension'] = 'Il formato definito per "{1}" non è valido.';
$l['error_field_minnamelength'] = 'Minimum name length can not be larger than maximum name length';
$l['error_field_minpasswordlength'] = 'Minimum password length can not be larger than maximum password length';
$l['error_field_minpasswordlength_complex'] = 'Minimum password length can not be less than 3 when using complex passwords';
$l['error_field_postmaxavatarsize'] = 'Maximum Avatar Dimensions';
$l['error_field_postmaxavatarsize'] = 'Dimensione massima dell\'avatar nei messaggi';
$l['error_field_useravatardims'] = 'Dimensioni avatar di default';
$l['error_field_maxavatardims'] = 'Dimensione massima avatar';
$l['error_field_memberlistmaxavatarsize'] = 'Massima dimensione visualizzazione avatar';
$l['error_missing_title'] = 'Non hai inserito il titolo della impostazione';
$l['error_missing_group_title'] = 'Non hai inserito il titolo del gruppo si impostazioni';
$l['error_invalid_gid'] = 'Non hai selezionato nessun gruppo dive inserire questa impostazione';
$l['error_invalid_gid2'] = 'Hai inserito il link a un gruppo non valido. Controlla che sia presente.';
$l['error_missing_name'] = 'Non hai inserito un identificativo per questa impostazione.';
$l['error_missing_group_name'] = 'Non hai inserito un identificativo per questo gruppo di impostazioni.';
$l['error_invalid_type'] = 'Non hai selezionato un tipo valido per questa impostazione';
$l['error_invalid_sid'] = 'La impostazione selezionata non esiste';
$l['error_duplicate_name'] = 'L\'identificativo inserito è già usato per l\'impostazione "{1}"  -- deve essere unico';
$l['error_duplicate_group_name'] = 'L\'identificativo inserito è gi%agrave; usato per il gruppo di impostazioni "{1}"  -- it must be unique';
$l['error_no_settings_found'] = 'Nessuna impostazione trovata con il valore inserito';
$l['error_cannot_edit_default'] = 'Le impostazioni e gruppi predefiniti non possono essere eliminati o modificati.';
$l['error_cannot_edit_php'] = 'Questa impostazione è di tipo speciale e non può essere modificata.';
$l['error_ajax_search'] = 'Vi sono problemi a cercare questa impostazione:';
$l['error_ajax_unknown'] = 'Errore sconosciuto durante la ricerca di questa impostazione.';
$l['error_chmod_settings_file'] = 'Il file delle impostazioni "./inc/settings.php" non è scrivibile. Per favore imposta il CHMOD a 666.<br />Per maggiori informazioni leggi le <a href="http://docs.mybb.com/HowTo_Chmod.html" target="_blank" rel="noopener">documentazioni di MyBB</a>.';
$l['error_admin_email_settings_empty'] = '<div class="smalltext" style="font-weight: normal;">Tieni presente che l\'<strong>email amministratore</strong> non è stata salvata in quanto l\'impostazione non può essere vuota e deve essere un indirizzo email valido.</div>';
$l['success_setting_added'] = 'Impostazione creata con successo.';
$l['success_setting_updated'] = 'Impostazione aggiornata con successo.';
$l['success_setting_deleted'] = 'Impostazione eliminata con successo.';
$l['success_settings_updated'] = 'Impostazioni aggiornate con successo.';
$l['success_settings_updated_hiddencaptchaimage'] = '<div class="smalltext" style="font-weight: normal;">Si prega di notare che l\'impostazione del <strong>campo Hidden CAPTCHA</strong> è stata ripristinata a <strong>{1}</strong> a causa di un conflitto con il campo <strong>{2}</strong> nel modulo della registrazione.</div>';
$l['success_settings_updated_username_method_conflict'] = '<div class="smalltext" style="font-weight: normal;">Si prega di notare che l\'impostazione <b>Metodi di accesso consentiti</b> non è stata aggiornata perché le email da registrare più volte sono attualmente consentite.</div>';
$l['success_settings_updated_username_method'] = '<div class="smalltext" style="font-weight: normal;">Si prega di notare che l\'impostazione <strong>Metodi d\'accesso ammessi</strong> non è stata aggiornata a causa di molteplici utenti che stanno utilizzando lo stesso indirizzo e-mail in questo momento.</div>';
$l['success_settings_updated_allowmultipleemails'] = '<div class="smalltext" style="font-weight: normal;">Si prega di notare che l\'impostazione <strong>Abilita l\'uso di una mail già registrata?</strong> non può essere attivata perché l\'impostazione <strong>Metodi d\'accesso ammessi</strong> permette agli utenti di accedere con l\'indirizzo e-mail.</div>';
$l['success_settings_updated_captchaimage'] = '<div class="smalltext" style="font-weight: normal;">Si prega di notare che l\'impostazione <strong>Immagine CAPTCHA per la registrazione e scrittura messaggi</strong> è stata ripristinata a <strong>CAPTCHA default di MyBB</strong> a causa della mancanza di chiavi pubbliche/private.</div>';
$l['success_settings_updated_minsearchword'] = '<div class="smalltext" style="font-weight: normal;">Tieni presente che l\'impostazione <strong>Lunghezza minima parola di ricerca</strong> è stata impostata in modo da corrispondere alla configurazione del sistema del database.</div>';
$l['success_display_orders_updated'] = 'Ordine di visualizzazione aggiornato.';
$l['success_setting_group_added'] = 'Il gruppo di impostazioni è stato aggiunto con successo.';
$l['success_setting_group_updated'] = 'Il gruppo di impostazioni è stato aggiornato con successo.';
$l['success_setting_group_deleted'] = 'Il gruppo di impostazioni è stato eliminato con successo.';
$l['success_duplicate_settings_deleted'] = 'Tutte le impostazioni duplicate sono state eliminate.';
$l['searching'] = 'Ricerca&hellip;';
$l['search_error'] = 'Si è verificato un errore durante il recupero dei risultati della ricerca:';
$l['search_done'] = 'Fatto!';