<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano
// Author of the language pack : Cesarinik
// Language pack translators website : https://github.com/cesarinik/
// Compatible version of MyBB : 1835
// Last edited in MyBB Editor by : cesarinik
// Last edited date : Tue, 18 Jul 2023 19:29:03 +0000
// --------------------------------------------------------------------------------

$l['thread_prefixes'] = 'Prefissi Discussione';
$l['thread_prefixes_desc'] = 'I prefissi discussione ti permettono di definire prefissi che gli utenti potranno assegnare alle proprie discussioni. Le discussioni potranno poi essere filtrate per prefisso all\'interno di un forum.';
$l['add_new_thread_prefix'] = 'Aggiungi un nuovo prefisso';
$l['add_new_thread_prefix_desc'] = 'Qui puoi aggiungere un nuovo prefisso discussione e definire dove sarÃ  utilizzabile, oltre a quale gruppo utente potrÃ  utilizzarlo.';
$l['edit_prefix'] = 'Modifica prefisso';
$l['edit_prefix_desc'] = 'Qui puoi modificare le impostazioni del prefisso: come sarÃ  mostrato, dove sarÃ  disponibile e quali gruppi utente potranno usarlo.';
$l['edit_thread_prefix'] = 'Modifica prefisso discussione';
$l['delete_thread_prefix'] = 'Elimina prefisso discussione';
$l['prefix_options'] = 'Opzioni prefisso';
$l['save_thread_prefix'] = 'Salva prefisso discussione';
$l['prefix'] = 'Prefisso';
$l['prefix_desc'] = 'Versione in testo semplice del prefisso da mostrare nel menu delle sezioni.';
$l['display_style'] = 'Stile di visualizzazione';
$l['display_style_desc'] = 'Questo Ã¨ come il prefisso apparirÃ  accanto all\'oggetto della discussione. Qui puoi inserire codice HTML o semplicemente inserire la stessa versione in testo semplice inserita sopra.';
$l['available_in_forums'] = 'Utilizzabile nei forum';
$l['available_to_groups'] = 'Utilizzabile dai gruppi';
$l['no_thread_prefixes'] = 'Non ci sono prefissi discussione sul tuo forum.';
$l['confirm_thread_prefix_deletion'] = 'Sei sicuro di voler eliminare questo prefisso discussione?Nota: Ricorda di aggiornare dopo l\'eliminazione qualsiasi strumento personalizzato di moderazione che utilizza questo prefisso.';
$l['success_thread_prefix_created'] = 'Il prefisso discussione Ã¨ stato creato.';
$l['success_thread_prefix_updated'] = 'Il prefisso discussione Ã¨ stato aggiornato.';
$l['success_thread_prefix_deleted'] = 'Il prefisso discussione Ã¨ stato eliminato Aggiorna qualsiasi strumento personalizzato di moderazione che utilizza questo prefisso.';
$l['error_missing_prefix'] = 'Inserisci il prefisso che desideri aggiungere.';
$l['error_missing_display_style'] = 'Inserisci lo stile di visualizzazione per questo prefisso.';
$l['error_no_forums_selected'] = 'Seleziona i forum in cui il prefisso sarÃ  disponibile.';
$l['error_no_groups_selected'] = 'Seleziona i gruppi utente a cui il prefisso sarÃ  disponibile.';
$l['error_invalid_prefix'] = 'Il prefisso discussione specificato non esiste.';
$l['forums'] = 'Forum';
$l['thread_prefixes_in'] = 'Prefissi Discussione in "{1}"';
