<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano
// Author of the language pack : Cesarinik
// Language pack translators website : https://github.com/cesarinik/
// Compatible version of MyBB : 1835
// Last edited in MyBB Editor by : cesarinik
// Last edited date : Tue, 18 Jul 2023 19:29:36 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = 'Registro Spam';
$l['spam_logs_desc'] = 'Questa sezione ti permette di vedere una cronologia con gli utenti bloccati dai filtri antispam.';
$l['prune_spam_logs'] = 'Sfoltisci registri spam';
$l['prune_spam_logs_desc'] = 'Qui puoi sfoltire i registri antispam che corrispondono ai criteri specificati.';
$l['spam_username'] = 'Nome utente';
$l['spam_email'] = 'Indirizzo email';
$l['spam_ip'] = 'Indirizzo IP';
$l['spam_date'] = 'Data';
$l['spam_confidence'] = 'Fiducia';
$l['no_spam_logs'] = 'Non ci sono ancora utenti bloccati dai filtri antispam.';
$l['success_pruned_spam_logs'] = 'I registri antispam sono stati sfoltiti con successo.';
$l['note_logs_locked'] = 'Per motivi di sicurezza non possono essere sfoltiti log con meno di 24 ore.';
$l['all_usernames'] = 'Tutti i nomi utente';
$l['all_emails'] = ' Tutti gli indirizzi email';
$l['date_range'] = 'Periodo:';
$l['days'] = 'giorni';
$l['filter_spam_logs'] = 'Filtra registri spam';
$l['asc'] = 'Crescente';
$l['desc'] = 'Decrescente';
$l['search_ip_on_sfs'] = 'Cerca questo IP su Stop Forum Spam';
$l['search'] = 'Cerca';
$l['in'] = 'in';
$l['order'] = 'ordine';
$l['sort_by'] = 'Inviato da';
$l['results_per_page'] = 'Risultati per pagina';
$l['older_than'] = 'Più vecchi di';

