<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Italiano
// Author of the language pack : Cesarinik
// Language pack translators website : https://github.com/cesarinik/
// Compatible version of MyBB : 1835
// Last edited in MyBB Editor by : cesarinik
// Last edited date : Tue, 18 Jul 2023 19:35:04 +0000
// --------------------------------------------------------------------------------

$l['warning_logs'] = 'Registro avvertimenti';
$l['warning_logs_desc'] = 'Questa sezione consente di visualizzare una cronologia degli avvertimenti assegnati agli utenti.';
$l['warned_user'] = 'Utente avvertito';
$l['warning'] = 'Avvertimento';
$l['date_issued'] = 'Data assegnazione';
$l['expires'] = 'Scadenza';
$l['expiry_date'] = 'Data scadenza';
$l['issued_date'] = 'Data assegnazione';
$l['issued_by'] = 'Assegnato da';
$l['details'] = 'Dettagli';
$l['filter_warning_logs'] = 'Filtra i registri degli avvertimenti';
$l['filter_warned_user'] = 'Utente avvertito:';
$l['filter_issued_by'] = 'Avvertito da:';
$l['filter_reason'] = 'La motivazione contiene:';
$l['sort_by'] = 'Ordina per:';
$l['results_per_page'] = 'Risultati per pagina:';
$l['view'] = 'Visualizza';
$l['no_warning_logs'] = 'Non ci sono registri di avvertimenti da visualizzare.';
$l['revoked'] = 'Revoca';
$l['post'] = 'Messaggio';
$l['asc'] = 'Crescente';
$l['desc'] = 'Decrescente';
$l['in'] = 'in';
$l['order'] = 'ordine';
$l['warning_details'] = 'Dettagli avvertimento';
$l['warning_note'] = 'Note amministrative';
$l['already_expired'] = 'Scaduto';
$l['warning_revoked'] = 'Revocato';
$l['warning_active'] = 'Attivo';
$l['error_invalid_warning'] = 'Hai specificato un avvertimento non valido.';
$l['revoke_warning'] = 'Revoca questo avvertimento';
$l['revoke_warning_desc'] = 'Per revocare questo avvertimento inserisci una motivazione qui di seguito. Questo non rimuoverà ban o sospensioni scatenate da questo avvertimento.';
$l['reason'] = 'Motivazione:';
$l['warning_is_revoked'] = 'Questo avvertimento è stato revocato';
$l['revoked_by'] = 'Revocato da:';
$l['date_revoked'] = 'Data revoca:';
$l['error_already_revoked'] = 'Questo avvertimento è stato già revocato.';
$l['error_no_revoke_reason'] = 'Non hai motivato la revoca dell\'avvertimento.';
$l['redirect_warning_revoked'] = 'L\'avvertimento è stato revocato ed i punti avvertimento dell\'utente sono stati diminuiti.';
$l['warning_points'] = '({1} punti)';
